[package]
name = "myrio-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
# internal
myrio-proc = { workspace = true }
# external
bio = { workspace = true }
bio-seq = { workspace = true }
bincode = { version = "2.0" }
bytemuck = { version = "1.23" }
flate2 = { version = "1.1" }
itertools = { workspace = true }
rand = { version = "0.9" }
rand_distr = { version = "0.5" }
thiserror = { version = "2.0" }
zstd = { version = "0.13" }

[dev-dependencies]
indoc = { version = "2.0" }
