[package]
name = "myrio-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
bio = { workspace = true }
bio-seq = { workspace = true }
bincode = { version = "2.0" }
flate2 = { version = "1.1" }
itertools = { workspace = true }
thiserror = { version = "2.0" }
zstd = { version = "0.13" }

[dev-dependencies]
indoc = { version = "2.0" }
