[package]
name = "myrio-proc"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
# external
quote = { version = "1.0" }
syn = { version = "2.0", features = ["full"] }
