[package]
name = "myrio-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme = "README.md"
categories = ["command-line-utilities"]

[dependencies]
# internal
myrio-core = { workspace = true }
# external
clap = { version = "4.5" }

[[bin]]
name = "myrio"
path = "src/main.rs"
